#ifndef _U_TYPES_H_
#define _U_TYPES_H_

enum {
	WAVE_NOISE = 0,
	WAVE_SIN,
	WAVE_SQUARE, 
	WAVE_SAWL,
	WAVE_SAWR,
	WAVE_TRIANGLE
};

typedef enum {
	KB_OSC1_WAVEFORM = 1, 
	KB_OSC1_DETUNE, 
	KB_OSC1_FINE_TUNE, 
	KB_OSC1_PHASE_OFFSET,
	KB_OSC2_WAVEFORM,
	KB_OSC2_DETUNE, 
	KB_OSC2_FINE_TUNE,
	KB_OSC2_PHASE_OFFSET,
	KB_OSC_MIX_AMOUNT,
	KB_LFO_SPEED,
	KB_LFO_TO_OSC,
	KB_LFO_TO_FILTER,
	KB_LFO_TO_AMP,
	KB_AMP_ENV_ATTACK,
	KB_AMP_ENV_DECAY,
	KB_AMP_ENV_SUSTAIN,
	KB_AMP_ENV_RELEASE,
	KB_FILTER_CUTOFF,
	KB_FILTER_ENV_AMOUNT,
	KB_FILTER_ATTACK,
	KB_FILTER_DECAY,
	KB_FILTER_SUSTAIN,
	KB_FILTER_RELEASE,
	KB_AMP_VOLUME,
	KB_OPTION_COUNT
} knob_t; 

#endif
